### ISSUE TITLE
could you add Split byte data into chunks to printer network? 

### ISSUE THREAD

**Issue by ul-rotha** [toannmdev/esc_pos_bluetooth#1]
could you add Split byte data into chunks to printer network? I meet problem when i have a big image. the printer stop print and print maybe 10% success after that the printer disconnect.

**Comment by toannmdev** [comment]
Hello @ul-rotha ,

This is a project which forked from this [link](https://github.com/andrey-ushakov/esc_pos_bluetooth)

You can check this issue in Readme.md:

`If your printer prints only 5%-10% of an image and then stops, or it can't print more than 1 image on the same ticket, or it can't print long tickets, try to ajust queueSleepTimeMs of the PrinterBluetoothManager.printTicket (try 50 or 100ms): printerManager.printTicket(await demoReceipt(paper), queueSleepTimeMs: 50);`

**Comment by ul-rotha** [comment]
> Hello @ul-rotha ,
> 
> This is a project which forked from this [link](https://github.com/andrey-ushakov/esc_pos_bluetooth)
> 
> You can check this issue in Readme.md:
> 
> `If your printer prints only 5%-10% of an image and then stops, or it can't print more than 1 image on the same ticket, or it can't print long tickets, try to ajust queueSleepTimeMs of the PrinterBluetoothManager.printTicket (try 50 or 100ms): printerManager.printTicket(await demoReceipt(paper), queueSleepTimeMs: 50);`

@toannmdev  Thanks
